#!/usr/bin/env python3
"""Generate the patch-control name-table include from the pinned inventory.

Emits ``tb/sv/gf180_patch_table.svh`` — the SystemVerilog fragment the
patch-control core (tb/sv/patch_control.sv) includes inside its module body:
the 78 canonical parameter names of
``spec/reference/parameter-inventory-v1.json`` in sorted canonical-name byte
order (the patch-hash walk order, spec/protocol/PATCH-LOAD.md), the pinned
name-table reference (SHA-256 of the inventory document bytes), the bound
numeric-contract version (the refusal-gated SHA-256 of the accepted DR-0008
choice register, identical to
``torchsynth_voice.core_protocol.numeric_contract_version_bound``), the
patch-hash domain tag, and the core's bound profile id.

Refusal gates: the numeric contract is read only through the acceptance
gate; the inventory must carry exactly 78 unique names, every name at most
``NAME_BYTES_MAX`` bytes, and both keyboard control names present. While a
gate refuses, generate mode writes nothing and exits 2 after naming the
refusal; ``--check`` treats exactly that state as success so CI can assert
the refusal without requiring ratification.

``--check`` compares exact UTF-8 bytes and never writes the output, so a
stale include after any inventory or register edit is a failure.

No synthesis or PDK step is involved anywhere: this tool emits plain
SystemVerilog source text or nothing, and makes no synthesis, PPA, fit, or
hardware claim.

Usage:
    python3 tools/generate_patch_names.py [--check] [--output PATH]
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from torchsynth_voice import golden_vectors as gv  # noqa: E402
from torchsynth_voice.core_protocol import (  # noqa: E402
    PATCH_HASH_DOMAIN,
    numeric_contract_version_bound,
)

DEFAULT_OUTPUT = ROOT / "tb/sv/gf180_patch_table.svh"

NAME_BYTES_MAX = 30
KEYBOARD_MIDI_NAME = "keyboard.midi_f0"
KEYBOARD_DURATION_NAME = "keyboard.duration"


def _hex_literal(data: bytes, width_bits: int) -> str:
    return "%d'h%0*x" % (width_bits, width_bits // 4, int.from_bytes(data, "big"))


def _name_literal(name: str) -> str:
    encoded = name.encode("utf-8")
    padded = encoded + b"\x00" * (NAME_BYTES_MAX - len(encoded))
    return _hex_literal(padded, NAME_BYTES_MAX * 8)


def build_include() -> str:
    inventory_bytes = gv.INVENTORY_PATH.read_bytes()
    inventory = gv.load_inventory_document()
    entries = inventory["parameters"]
    names = sorted(entry["name"] for entry in entries)
    if len(names) != 78:
        raise SystemExit(
            "REFUSED: inventory carries %d names, expected 78" % len(names)
        )
    if len(set(names)) != len(names):
        raise SystemExit("REFUSED: inventory names are not unique")
    too_long = [name for name in names if len(name.encode("utf-8")) > NAME_BYTES_MAX]
    if too_long:
        raise SystemExit(
            "REFUSED: names exceed the %d-byte name window: %r"
            % (NAME_BYTES_MAX, too_long)
        )
    for required in (KEYBOARD_MIDI_NAME, KEYBOARD_DURATION_NAME):
        if required not in names:
            raise SystemExit("REFUSED: inventory lacks %s" % required)

    table_sha = hashlib.sha256(inventory_bytes).digest()
    contract = numeric_contract_version_bound()
    profile = inventory["profile"].encode("utf-8")
    if not 1 <= len(profile) <= 64:
        raise SystemExit(
            "REFUSED: inventory profile %r outside the 1..64-byte window"
            % inventory["profile"]
        )

    lines = [
        "// Generated by tools/generate_patch_names.py -- DO NOT EDIT.",
        "// Source of truth: spec/reference/parameter-inventory-v1.json",
        "// (SHA-256 %s), consumed through spec/PARAMETER-INVENTORY.md;"
        % table_sha.hex(),
        "// numeric contract: the accepted DR-0008 register through the",
        "// refusal gate (identical to core_protocol.numeric_contract_version_bound).",
        "// Names are stored left-justified (first byte at the MSB) in sorted",
        "// canonical-name byte order == the patch-hash walk order.",
        "localparam integer NUM_PARAMS = %d;" % len(names),
        "localparam integer NAME_BYTES = %d;" % NAME_BYTES_MAX,
        "localparam integer KBD_MIDI_SLOT = %d;" % names.index(KEYBOARD_MIDI_NAME),
        "localparam integer KBD_DUR_SLOT = %d;" % names.index(KEYBOARD_DURATION_NAME),
        "localparam [255:0] NAME_TABLE_SHA256 = %s;"
        % _hex_literal(table_sha, 256),
        "localparam [255:0] NUMERIC_CONTRACT_VERSION = %s;"
        % _hex_literal(contract, 256),
        "localparam [(%d*8)-1:0] PATCH_DOMAIN_TAG = %s;"
        % (len(PATCH_HASH_DOMAIN), _hex_literal(PATCH_HASH_DOMAIN, len(PATCH_HASH_DOMAIN) * 8)),
        "localparam integer DOMAIN_TAG_LEN = %d;" % len(PATCH_HASH_DOMAIN),
        "localparam [(%d*8)-1:0] PROFILE_ID = %s;"
        % (len(profile), _hex_literal(profile, len(profile) * 8)),
        "localparam integer PROFILE_ID_LEN = %d;" % len(profile),
        "",
        "reg [(%d*8)-1:0] name_rom [0:NUM_PARAMS-1];" % NAME_BYTES_MAX,
        "reg [7:0] name_len_rom [0:NUM_PARAMS-1];",
        "initial begin",
    ]
    for slot, name in enumerate(names):
        lines.append(
            "    name_rom[%d] = %s;" % (slot, _name_literal(name))
        )
        lines.append(
            "    name_len_rom[%d] = 8'd%d;"
            % (slot, len(name.encode("utf-8")))
        )
    lines.append("end")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the gates; succeed when the honest state is reproduced",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="include path (default %(default)s)",
    )
    args = parser.parse_args(argv)

    try:
        text = build_include()
    except SystemExit as error:
        if args.check:
            print("CHECK: %s" % error)
            return 0
        print(error, file=sys.stderr)
        return 2

    if args.check:
        landed = args.output.read_text(encoding="utf-8")
        if landed != text:
            print(
                "CHECK FAILED: %s does not match the live emission of the "
                "pinned inventory + accepted register; regenerate it"
                % args.output
            )
            return 1
        print(
            "CHECK OK: %s matches the pinned inventory (%d names) and the "
            "accepted numeric register" % (args.output, 78)
        )
        return 0

    args.output.write_text(text, encoding="utf-8")
    print(
        "wrote %s (%d names, table %s)"
        % (args.output, 78, hashlib.sha256(gv.INVENTORY_PATH.read_bytes()).hexdigest()[:16])
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
